title: Jason's Blog
tagline: 生活需要仪式感。
description: 一个程序员的技术和生活
baseurl: /jekyll_demo # the subpath of your site, e.g. /blog/
url: https://jasonariana.github.io # the base hostname & protocol for your site

author:
  name: Jason
  email: hjrr140418@163.com
  github: jasonariana
start_year: 2017

permalink: /:year/:month/:day/:title
timezone: Asia/Shanghai

tags_path: /tags.html
feed_path: /feed.xml

markdown: kramdown
# highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: [README.md]
  
